# Generated by Django 5.2.5 on 2025-08-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(choices=[('empleado', 'empleado'), ('cliente', 'cliente'), ('administrador', 'administrador')], max_length=15)),
            ],
            options={
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('id_personal', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='usuario.tipo')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
